let myDate = new Date()
console.log(myDate)
console.log(String(myDate))
console.log(myDate.toString())
console.log(myDate.toDateString())
console.log(myDate.toJSON())
console.log(myDate.toLocaleDateString())
console.log(myDate.toLocaleTimeString())
console.log(myDate.toTimeString())
console.log(myDate.toUTCString())

let myNewDate = new Date(2024,8,13)
console.log(myNewDate)
console.log(myNewDate.toDateString())

let myNewDated = new Date(2024,8,13,11,50)
console.log("The latest date is", myNewDate.toLocaleString())

let myNewDateds = new Date("2024-05-13")
console.log(myNewDateds.toLocaleString())

let myTimestamp = new Date()
console.log(myTimestamp.now)

let myTimestamp1 = Date.now()
console.log(myTimestamp1)

let newDate = new Date()
console.log(newDate.getDate())
console.log(newDate.getDay())
console.log(newDate.getFullYear())
console.log(newDate.getHours())
console.log(newDate.getMilliseconds())
console.log(newDate.getMonth())
console.log(newDate.getTime())